version: '3.8'

services:
    backend:
        build: ./backend
        container_name: ddc_backend_c
        volumes:
            - ./backend:/app
            - /app/node_modules
        ports:
            - '3000:3000'
        env_file:
            - ./backend/.env
