version: '3.8'

services:
    backend:
        build: ./backend
        container_name: ddc_backend_c
        volumes:
            - ./backend:/app
            - /app/node_modules
        ports:
            - '3000:3000'
        env_file:
            - ./backend/.env

        depends_on:
            - redis
        networks:
            - app-network
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'
        networks:
            - app-network

    frontend:
        build: ./frontend/digitaldocvault
        container_name: ddc_frontend_c
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - '5000:5000'
        depends_on:
            - backend
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
